# Generated by Django 4.1.3 on 2022-11-07 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appfamily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parents',
            name='birth',
            field=models.CharField(max_length=10),
        ),
    ]
